---
version: '3'

services:
  wombo:
    container_name: "wombo_bot"
    image: "ghcr.io/axsddlr/wombo_bot:latest"
    restart: unless-stopped
    # choose time zone for bot
    environment:
      - TZ=America/New_York
    volumes:
      - ./r_hls/config.json:/hls_bot/config.json