styles = {
    "synthwave": "1",
    "ukiyoe": "2",
    "nostyle": "3",
    "steampunk": "4",
    "fantasyart": "5",
    "vibrant": "6",
    "hd": "7",
    "pastel": "8",
    "psychic": "9",
    "darkfantasy": "10",
    "mystical": "11",
    "festive": "12",
    "baroque": "13",
    "etching": "14",
    "sdali": "15",
    "wuhtercuhler": "16",
    "provenance": "17",
    "rosegold": "18",
    "moonwalker": "19",
    "blacklight": "20",
    "psychedelic": "21",
    "ghibil": "22",

}
